#!/bin/bash

START=$(date +%s)

echo Generating color map and tiles for urban footprint t0 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/urban_footprint/t0.img gis/urban_footprint_color_table gis/sample/urban_footprint/t0.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/urban_footprint/t0.tiff public/tiles/sample/urban_footprint/t0
echo

echo Generating color map and tiles for urban footprint t1 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/urban_footprint/t1.img gis/urban_footprint_color_table gis/sample/urban_footprint/t1.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/urban_footprint/t1.tiff public/tiles/sample/urban_footprint/t1
echo

echo Generating color map and tiles for urban footprint t2 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/urban_footprint/t2.img gis/urban_footprint_color_table gis/sample/urban_footprint/t2.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/urban_footprint/t2.tiff public/tiles/sample/urban_footprint/t2
echo

echo Generating color map and tiles for urban area t0 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/urban_area/t0.img gis/urban_area_color_table gis/sample/urban_area/t0.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/urban_area/t0.tiff public/tiles/sample/urban_area/t0
echo

echo Generating color map and tiles for urban area t1 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/urban_area/t1.img gis/urban_area_color_table gis/sample/urban_area/t1.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/urban_area/t1.tiff public/tiles/sample/urban_area/t1
echo

echo Generating color map and tiles for urban area t2 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/urban_area/t2.img gis/urban_area_color_table gis/sample/urban_area/t2.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/urban_area/t2.tiff public/tiles/sample/urban_area/t2
echo

echo Generating color map and tiles for new development t0-t1 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/new_development/t0_t1.img gis/new_development_color_table gis/sample/new_development/t0_t1.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/new_development/t0_t1.tiff public/tiles/sample/new_development/t0_t1
echo

echo Generating color map and tiles for new development t1-t2 layer for zoom levels between $1 and $2...
gdaldem color-relief gis/sample/new_development/t1_t2.img gis/new_development_color_table gis/sample/new_development/t1_t2.tiff -alpha -b 1 -of GTiff
gdal2tiles.py -z $1-$2 -w none gis/sample/new_development/t1_t2.tiff public/tiles/sample/new_development/t1_t2
echo

END=$(date +%s)
DIFF=$(( $END - $START ))
echo "Tiles generated in $DIFF seconds!"